from typing import List, Dict, Any, Optional
from langchain_core.messages import BaseMessage
from typing import List, Dict, Any, Optional, TypedDict

class AgentState(TypedDict):
    """
    Represents the state of the LangGraph agent during portfolio analysis.

    Attributes:
        documents (List[Dict[str, Any]]): A list of dictionaries, where each dictionary
                                          represents a loaded document. Each document
                                          should have at least 'content' and 'metadata' keys.
        sections_to_process (List[str]): A list of section titles that still need to be
                                         processed by the agent (e.g., "Overview", "Financial Review").
        completed_sections (List[Dict[str, Any]]): A list of dictionaries, where each
                                                   dictionary represents a completed section
                                                   of the analysis, including its content,
                                                   sub_sections, references, key_highlights, and any other relevant metadata.
        current_section (Optional[str]): The title of the section currently being processed.
                                         None if no section is currently active.
        current_section_instruction (Optional[str]): Additional instruction for the LLM for the current section.
        loop_count (int): The current iteration count for the review loop of the
                          `current_section`. Used to limit the number of review cycles.
        critique (Optional[Dict[str, Any]]): The critique generated by the Reviewer Node
                                            for the `current_section`. Contains feedback
                                            and search terms for refinement.
        key_highlights (List[str]): A list of key highlights extracted from the current section.
        messages (List[BaseMessage]): A list of messages exchanged during the agent's
                                       execution, useful for debugging and tracing.
        current_section_content (Optional[str]): The content of the current section being processed.
        current_section_references (List[Dict[str, Any]]): References for the current section.
        tabular_data (Optional[Dict[str, Any]]): Stores generated tabular data for the current section.
        graph_specs (Optional[List[Dict[str, Any]]]): Stores a list of generated graph specifications for the current section.
    """
    documents: List[Dict[str, Any]]
    sections_to_process: List[Dict[str, str]] # Updated to expect dicts with title and instruction
    completed_sections: List[Dict[str, Any]] # Each item will now include 'key_highlights'
    current_section: Optional[str]
    current_section_instruction: Optional[str]
    include_table: bool # Added to control table generation
    table_instructions: Optional[str] # Added for table generation instructions
    include_graphs: bool # Added to control graph generation
    graph_instructions: Optional[str] # Added for graph generation instructions
    loop_count: int
    critique: Optional[Dict[str, Any]]
    key_highlights: List[str] # Added key_highlights as a top-level field
    current_section_content: Optional[str]
    current_section_references: List[Dict[str, Any]]
    current_section_sub_sections: List[Dict[str, Any]] # Added to persist structured sub-sections
    tabular_data: Optional[Dict[str, Any]]
    graph_specs: Optional[List[Dict[str, Any]]] # Changed to graph_specs (plural) and type to List
    messages: List[BaseMessage]